apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdi-runner-dvc-cache
  namespace: cdi-runner
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
