apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cdi-runner
  namespace: cdi-runner
spec:
  template:
    spec:
      nodeSelector:
        part-of: actions-runner
      tolerations:
        - key: "part-of"
          operator: "Equal"
          value: "actions-runner"
          effect: "NoSchedule"
      repository: ipno-llead/processing
      image: ghrunner
      labels:
        - cdi-runner
      env: []
      resources:
        limits:
          cpu: "1.0"
          memory: "8Gi"
        requests:
          cpu: "0.5"
          memory: "4Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cdi-runner-data
      volumeMounts:
        - mountPath: /runner/_work/data
          name: data
