apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cdi-runner
  namespace: cdi-runner
spec:
  template:
    spec:
      repository: ppact/processing
      image: ghrunner
      labels:
        - cdi-runner
      env: []
      resources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "2.0"
          memory: "4Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cdi-runner-data
      volumeMounts:
        - mountPath: /runner/_work/data
          name: data
