dataDir: data
patterns:
  prerequisites:
    - pd.read_csv(deba.data(r'.+\.csv'))
  targets:
    - "`*`.to_csv(deba.data(r'.+\\.csv'))"
stages:
  - name: meta
  - name: ocr
  - name: ner
  - name: clean
    ignoredTargets:
      - duplicates.csv
  - name: match
  - name: fuse
    ignoredTargets:
      - duplicates.csv
      - fuse/person.csv
    commonPrerequisites:
      - datavalid.yml
targets:
  - fuse/personnel.csv
  - fuse/allegation.csv
  - fuse/use_of_force.csv
  - fuse/stop_and_search.csv
  - fuse/appeals.csv
  - fuse/event.csv
overrides:
  - target:
      - meta/minutes_files.csv
    prerequisites:
      - $(DEBA_MD5_DIR)/meta/minutes.py.md5
      - $(DEBA_MD5_DIR)/raw_minutes.dvc.md5
    recipe: "$(call deba_execute,meta/minutes.py)"
  - target:
      - meta/post_officer_history_reports_files.csv
    prerequisites:
      - $(DEBA_MD5_DIR)/meta/post_officer_history_reports.py.md5
      - $(DEBA_MD5_DIR)/raw_post_officer_history_reports.dvc.md5 
    recipe: "$(call deba_execute,meta/post_officer_history_reports.py)"
  - target:
      - meta/nopd_pib_reports_files_2014_2019.csv
    prerequisites:
      - $(DEBA_MD5_DIR)/meta/nopd_pib_reports.py.md5
      - $(DEBA_MD5_DIR)/raw_nopd_pib_reports.dvc.md5 
    recipe: "$(call deba_execute,meta/nopd_pib_reports.py)"
