dataDir: data
patterns:
  inputs:
    - pd.read_csv(dirk.data(r'.+\.csv'))
  outputs:
    - "`*`.to_csv(dirk.data(r'.+\\.csv'))"
stages:
  - name: clean
    ignoredOutputs:
      - duplicates.csv
  - name: match
  - name: fuse
    ignoredOutputs:
      - duplicates.csv
      - fuse/person.csv
targets:
  - fuse/personnel.csv
  - fuse/allegation.csv
  - fuse/use_of_force.csv
  - fuse/stop_and_search.csv
  - fuse/appeals.csv
  - fuse/event.csv
