name: Process Data
on:
  push:
    branches:
      - enhancement/gh-k8s-runner
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - main
jobs:
  process-data:
    runs-on: cdi-runner
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: install wrgl
        run: sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
      - name: dvc pull
        run: dvc pull data/raw -r gcs
      - run: wrgl pull --all
      - name: process data
        run: make
      - name: commit changes in transaction
        id: transaction
        run: |
          wrgl transaction start | tr -d "[:space:]" > txid.txt
          wrgl commit --all --txid $(cat txid.txt) "PR #${PR}: ${PR_TITLE}\nhttps://github.com/${GITHUB_REPOSITORY}/pull/${PR}"
          wrgl transaction push origin $(cat txid.txt)
          echo "::set-output name=txid::$(cat txid.txt)"
          echo "::set-output name=txURL::https://hub.wrgl.co/$(wrgl remote -v | grep origin | sed -E 's/.+\/api\/users\/(.+)\/repos\/(.+)/@\1\/r\/\2/')/tx/$(cat txid.txt)"
        env:
          PR: ${{ steps.findPr.outputs.pr }}
          PR_TITLE: ${{ steps.findPr.outputs.title }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Review data changes at [tx/${{ steps.transaction.outputs.txid }}][1]

            When this PR is merged, this transaction will be applied.

            [1]: ${{ steps.transaction.outputs.txURL }}
