name: Process Data
on:
  pull_request:
    branches:
      - main
jobs:
  process-data:
    runs-on: cdi-runner
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: "pip"
      - name: install make
        run: |
          curl http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.3-4ubuntu1_amd64.deb > ~/make_4.3-4ubuntu1_amd64.deb
          sudo apt-get install ~/make_4.3-4ubuntu1_amd64.deb
      - run: pip install -r requirements.txt
      - name: install wrgl
        run: sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
      - name: dvc pull
        run: |
          sed -iE 's/path\: data/path\: \/runner\/_work\/data\/data/g' raw.dvc
          mkdir /runner/_work/data/dvc_cache || true
          dvc cache dir --local /runner/_work/data/dvc_cache
          dvc pull
      - name: wrgl pull
        run: |
          wrgl config set --global user.email "gh-action@publicdata.works"
          wrgl config set --global user.name "Github Action"
          mkdir /runner/_work/data/.wrgl || true
          cp .wrgl/config.yaml /runner/_work/data/.wrgl/
          wrgl init --wrgl-dir /runner/_work/data/.wrgl || true
          wrgl pull --wrgl-dir /runner/_work/data/.wrgl --all
      - name: process data
        run: |
          sed -iE 's/dataDir\: data/dataDir\: \/runner\/_work\/data\/data/g' deba.yaml
          echo "md5Dir: /runner/_work/data/md5" >> deba.yaml
          make WRGL_FLAGS="--wrgl-dir /runner/_work/data/.wrgl"
      - name: commit changes in transaction
        id: transaction
        run: |
          cd /runner/_work/data
          echo "${WRGLHUB_TOKEN}" > token.txt
          wrgl credentials authenticate https://hub.wrgl.co/api --token-location token.txt
          rm token.txt
          wrgl transaction start | tr -d "[:space:]" > txid.txt
          wrgl commit --all --txid $(cat txid.txt) "PR #${PR}: ${PR_TITLE}\nhttps://github.com/${GITHUB_REPOSITORY}/pull/${PR}"
          wrgl transaction push origin $(cat txid.txt)
          echo "::set-output name=txid::$(cat txid.txt)"
          echo "::set-output name=txURL::https://hub.wrgl.co/$(wrgl remote -v | grep origin | sed -E 's/.+\/api\/users\/(.+)\/repos\/(.+)/@\1\/r\/\2/')/tx/$(cat txid.txt)"
        env:
          WRGLHUB_TOKEN: ${{ secrets.WRGLHUB_TOKEN }}
          PR: ${{ steps.findPr.outputs.pr }}
          PR_TITLE: ${{ steps.findPr.outputs.title }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Review data changes at [tx/${{ steps.transaction.outputs.txid }}][1]

            When this PR is merged, this transaction will be applied.

            [1]: ${{ steps.transaction.outputs.txURL }}
  apply-transaction:
    runs-on: cdi-runner
    needs: process-data
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - name: Find transaction comment
        uses: peter-evans/find-comment@v2.0.0
        id: fc
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          comment-author: github-actions[bot]
          body-includes: Review data changes at
          direction: last
      - name: Extract transaction url
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        id: txURL
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.fc.outputs.comment-body }}
          regex: |
            .+(https://hub\.wrgl\.co\/@.+)
          flags: "s"
          replacement: $1
      - name: Extract transaction id
        if: ${{ steps.txURL.outputs.value != null }}
        id: txid
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.txURL.outputs.value }}
          regex: .+\/tx\/(.+)
          flags: "" # Optional, defaults to "g"
          replacement: $1
      - name: Extract repo url
        if: ${{ steps.txURL.outputs.value != null }}
        id: repoURL
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.txURL.outputs.value }}
          regex: |
            https://hub\.wrgl\.co\/@(.+)\/r\/([^/]+).+
          flags: "" # Optional, defaults to "g"
          replacement: https://hub.wrgl.co/api/users/$1/repos/$2
      - name: Apply transaction
        if: ${{ steps.txid.outputs.value != null && steps.repoURL.outputs.value != null }}
        run: |
          echo "To ${REPO_URL}/transactions/${TXID}/"
          curl --fail-with-body -XPOST ${REPO_URL}/transactions/${TXID}/ \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${WRGLHUB_TOKEN}" \
          -d '{"commit":true}'
        env:
          WRGLHUB_TOKEN: ${{ secrets.WRGLHUB_TOKEN }}
          TXID: ${{ steps.txid.outputs.value }}
          REPO_URL: ${{ steps.repoURL.outputs.value }}
      - name: Create comment
        if: ${{ steps.txURL.outputs.value != null }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Transaction [tx/${{ steps.txid.outputs.value }}][1] applied.

            [1]: ${{ steps.txURL.outputs.value }}
