name: Process Data
on:
  push:
    branches:
      - enhancement/gh-k8s-runner
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - main
jobs:
  process-data:
    runs-on: cdi-runner
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: "pip"
      - name: install make
        run: |
          curl http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.3-4ubuntu1_amd64.deb > ~/make_4.3-4ubuntu1_amd64.deb
          sudo apt-get install ~/make_4.3-4ubuntu1_amd64.deb
      - run: pip install -r requirements.txt
      - name: install wrgl
        run: sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
      - name: dvc pull
        run: |
          sed -iE 's/path\: data/path\: \/runner\/_work\/data/g' raw.dvc
          dvc cache dir --local /runner/_work/.dvc/cache
          dvc pull
      - name: wrgl pull
        run: |
          wrgl config set --global user.email "gh-action@publicdata.works"
          wrgl config set --global user.name "Github Action"
          cp .wrgl/config.yaml /runner/_work/.wrgl/
          wrgl init --wrgl-dir /runner/_work/.wrgl || true
          wrgl pull --wrgl-dir /runner/_work/.wrgl --all
      - name: process data
        run: |
          sed -iE 's/dataDir\: data/dataDir\: \/runner\/_work\/data/g' deba.yaml
          make WRGL_FLAGS="--wrgl-dir /runner/_work/.wrgl"
      - name: commit changes in transaction
        id: transaction
        run: |
          cd /runner/_work/
          wrgl transaction start | tr -d "[:space:]" > txid.txt
          wrgl commit --all --txid $(cat txid.txt) "PR #${PR}: ${PR_TITLE}\nhttps://github.com/${GITHUB_REPOSITORY}/pull/${PR}"
          wrgl transaction push origin $(cat txid.txt)
          echo "::set-output name=txid::$(cat txid.txt)"
          echo "::set-output name=txURL::https://hub.wrgl.co/$(wrgl remote -v | grep origin | sed -E 's/.+\/api\/users\/(.+)\/repos\/(.+)/@\1\/r\/\2/')/tx/$(cat txid.txt)"
        env:
          PR: ${{ steps.findPr.outputs.pr }}
          PR_TITLE: ${{ steps.findPr.outputs.title }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Review data changes at [tx/${{ steps.transaction.outputs.txid }}][1]

            When this PR is merged, this transaction will be applied.

            [1]: ${{ steps.transaction.outputs.txURL }}
